In [42]:
import torch
from torch.nn import functional as F

#### self attention as matrix multiplication??

attention as soft dictionary lookup and may be a differentiable lookup operation

In [46]:
# b: batch size
# t: input size
# k: dimension size
b, t, k = 5, 5, 5
batch_sents = torch.randn(b, t, k)
batch_sents

tensor([[[-0.2698, -1.8379, -0.7919, -0.4819, -0.9430],
         [-1.6451, -1.4366,  0.8457, -0.2111, -0.2941],
         [-0.0422, -0.5662, -0.0157,  0.6143, -0.8865],
         [-0.9551,  0.2720, -0.6840, -1.1846,  0.8973],
         [ 0.0586,  0.5452, -0.1786, -0.9561,  0.6131]],

        [[ 0.8012, -1.3245,  0.9928, -0.2730, -0.6286],
         [ 0.7609, -0.6339,  0.1725, -0.0794, -1.3062],
         [-2.1067,  1.1425, -1.0729,  0.3460, -1.7464],
         [-0.0176, -0.0893, -0.1117,  0.6273, -1.4041],
         [ 0.2264,  0.0201, -1.1191,  0.5154, -0.3442]],

        [[ 0.5713, -0.1358,  0.5123,  0.2484, -0.4717],
         [ 0.0741,  0.8084,  0.1036, -0.3794,  0.4661],
         [ 0.4983, -1.6952,  0.0322, -0.3938, -0.6850],
         [-0.3818, -0.1766,  0.2442,  0.0202,  0.0535],
         [ 0.2928, -1.2908,  1.8345, -0.6009, -0.7956]],

        [[ 0.6560, -1.3898,  0.2385, -1.1189, -2.3544],
         [-0.1353,  0.3712,  1.5856,  0.3834, -0.9002],
         [-1.7945, -0.1015, -1.4671, -1.22

In [47]:
transpose_batch_sents = batch_sents.transpose(dim0=1, dim1=2)
transpose_batch_sents

tensor([[[-0.2698, -1.6451, -0.0422, -0.9551,  0.0586],
         [-1.8379, -1.4366, -0.5662,  0.2720,  0.5452],
         [-0.7919,  0.8457, -0.0157, -0.6840, -0.1786],
         [-0.4819, -0.2111,  0.6143, -1.1846, -0.9561],
         [-0.9430, -0.2941, -0.8865,  0.8973,  0.6131]],

        [[ 0.8012,  0.7609, -2.1067, -0.0176,  0.2264],
         [-1.3245, -0.6339,  1.1425, -0.0893,  0.0201],
         [ 0.9928,  0.1725, -1.0729, -0.1117, -1.1191],
         [-0.2730, -0.0794,  0.3460,  0.6273,  0.5154],
         [-0.6286, -1.3062, -1.7464, -1.4041, -0.3442]],

        [[ 0.5713,  0.0741,  0.4983, -0.3818,  0.2928],
         [-0.1358,  0.8084, -1.6952, -0.1766, -1.2908],
         [ 0.5123,  0.1036,  0.0322,  0.2442,  1.8345],
         [ 0.2484, -0.3794, -0.3938,  0.0202, -0.6009],
         [-0.4717,  0.4661, -0.6850,  0.0535, -0.7956]],

        [[ 0.6560, -0.1353, -1.7945, -0.0692,  0.7034],
         [-1.3898,  0.3712, -0.1015,  0.6030, -0.4841],
         [ 0.2385,  1.5856, -1.4671, -0.49

In [48]:
alpha = torch.matmul(batch_sents, transpose_batch_sents)
alpha

tensor([[[ 5.1992,  2.7935,  1.6044,  0.0242, -0.9938],
         [ 2.7935,  5.6166,  1.0007,  0.5881, -1.0093],
         [ 1.6044,  1.0007,  1.4860, -1.6262, -1.4393],
         [ 0.0242,  0.5881, -1.6262,  3.6624,  1.8973],
         [-0.9938, -1.0093, -1.4393,  1.8973,  1.6227]],

        [[ 3.8518,  2.4634, -3.2630,  0.7048, -0.8806],
         [ 2.4634,  2.7230, -0.2586,  1.8082,  0.3751],
         [-3.2630, -0.2586, 10.0641,  2.7241,  1.5262],
         [ 0.7048,  1.8082,  2.7241,  2.3857,  0.9258],
         [-0.8806,  0.3751,  1.5262,  0.9258,  1.6882]],

        [[ 0.8916, -0.3285,  0.7568, -0.0893,  1.5085],
         [-0.3285,  1.0308, -1.4999, -0.1284, -0.9745],
         [ 0.7568, -1.4999,  3.7473,  0.0723,  3.1748],
         [-0.0893, -0.1284,  0.0723,  0.2399,  0.5094],
         [ 1.5085, -0.9745,  3.1748,  0.5094,  6.1114]],

        [[ 9.2139,  1.4640,  4.4891, -3.2875,  5.3058],
         [ 1.4640,  3.6277, -0.8686, -1.7759,  1.1552],
         [ 4.4891, -0.8686, 10.5442, -0.93

In [49]:
att_scores = F.softmax(alpha, dim=2)
att_scores

tensor([[[8.8860e-01, 8.0156e-02, 2.4406e-02, 5.0260e-03, 1.8160e-03],
         [5.5167e-02, 9.2834e-01, 9.1844e-03, 6.0797e-03, 1.2307e-03],
         [3.9647e-01, 2.1678e-01, 3.5218e-01, 1.5674e-02, 1.8895e-02],
         [2.1061e-02, 3.7016e-02, 4.0432e-03, 8.0081e-01, 1.3707e-01],
         [2.9134e-02, 2.8685e-02, 1.8659e-02, 5.2476e-01, 3.9876e-01]],

        [[7.6801e-01, 1.9159e-01, 6.2438e-04, 3.3009e-02, 6.7624e-03],
         [3.3273e-01, 4.3137e-01, 2.1877e-02, 1.7280e-01, 4.1228e-02],
         [1.6282e-06, 3.2849e-05, 9.9912e-01, 6.4842e-04, 1.9572e-04],
         [5.5050e-02, 1.6594e-01, 4.1469e-01, 2.9565e-01, 6.8671e-02],
         [2.8778e-02, 1.0103e-01, 3.1940e-01, 1.7523e-01, 3.7556e-01]],

        [[2.2742e-01, 6.7133e-02, 1.9873e-01, 8.5278e-02, 4.2144e-01],
         [1.4390e-01, 5.6030e-01, 4.4599e-02, 1.7577e-01, 7.5423e-02],
         [3.0552e-02, 3.1988e-03, 6.0791e-01, 1.5410e-02, 3.4293e-01],
         [1.5757e-01, 1.5151e-01, 1.8520e-01, 2.1899e-01, 2.8673e-01],
  

In [68]:
# sanity check
print(att_scores[0][0][0].item())
print((alpha[0][0][0].exp() / torch.sum(torch.tensor([t.exp() for t in alpha[0][0]]))).item())

0.8885957598686218
0.888595700263977


In [75]:
z = torch.matmul(att_scores, batch_sents)
z

tensor([[[-0.3773, -1.7598, -0.6400, -0.4378, -0.8775],
         [-1.5482, -1.4379,  0.7369, -0.2253, -0.3270],
         [-0.4923, -1.2250, -0.1502, -0.0571, -0.7242],
         [-0.8236,  0.1984, -0.5577, -1.0952,  0.7683],
         [-0.5337,  0.2548, -0.4293, -1.0115,  0.6629]],

        [[ 0.7608, -1.1408,  0.7836, -0.2004, -0.7828],
         [ 0.5550, -0.7038,  0.3158,  0.0121, -1.0676],
         [-2.1048,  1.1414, -1.0722,  0.3462, -1.7459],
         [-0.6929,  0.2706, -0.4715,  0.3361, -1.4143],
         [-0.4910,  0.2547, -0.7365,  0.3981, -1.0832]],

        [[ 0.3248, -0.8726,  0.9238, -0.2988, -0.5429],
         [ 0.1009,  0.2294,  0.3145, -0.2362,  0.1121],
         [ 0.4151, -1.4775,  0.6684, -0.4388, -0.7014],
         [ 0.1939, -0.6217,  0.6819, -0.2591, -0.3470],
         [ 0.3031, -1.2946,  1.7257, -0.5803, -0.7831]],

        [[ 0.6355, -1.3603,  0.2142, -1.0912, -2.3420],
         [-0.0172,  0.1417,  1.2929,  0.2187, -1.1122],
         [-1.7879, -0.1047, -1.4627, -1.22